-- ====================================================================
-- INSERT paper3-methodology chapters into ssot_brochure.chapters
-- Generated by: gen_inserts.py
-- Requires: 2026-06-08-multi-doc.sql migration applied first
-- Doc slug: paper3-methodology (9 chapters)
-- ====================================================================

BEGIN;

-- Preflight: migration applied?
DO $check$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='ssot_brochure' AND table_name='chapters' AND column_name='doc'
  ) THEN
    RAISE EXCEPTION 'Migration 2026-06-08-multi-doc not applied: column doc missing';
  END IF;
END $check$;

-- Preflight: no existing paper3-methodology rows (idempotency)
DO $check$
DECLARE n int;
BEGIN
  SELECT COUNT(*) INTO n FROM ssot_brochure.chapters WHERE doc='paper3-methodology';
  IF n > 0 THEN
    RAISE EXCEPTION 'paper3-methodology already has % rows -- delete first or use UPDATE', n;
  END IF;
END $check$;

-- paper3-01-introduction (371 words, SHA-256 121b2d6639cf457e...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-01-introduction',
  'chapter',
  200100,
  'Introduction',
  $p3body_10$# Introduction

**Claim status:** Verified.

\label{sec:intro}

Imagine a machinist who needs to fit a component to a lathe specification, but
the measuring ruler in hand uses units that differ subtly from those in the
drawing.  The part may look correct; the divergence only surfaces under load.
The same scenario plays out in ML accelerator firmware: two chips may both claim
``FP8 E4M3 support'', yet differ silently in how they handle the overflow case
for an input such as $1000.0$ -- one saturates to max-finite $448.0$, the other
flips to NaN.  The OCP Microscaling specification [ocp_mx] permits both
choices.  Without a shared bit-exact reference, a ported model may produce
numerically different results that are difficult to isolate.

This paper describes two artifacts designed to serve as that shared ruler.

**Contribution 1: An 84-format numeric catalog..** 
The `t27` catalog enumerates 84 numeric formats across 13 families
(Section \ref{sec:catalog}).  Each entry carries a uniform schema: bit layout,
bias, infinity/NaN policy, saturation policy, max-finite value, min-normal,
min-subnormal, and a claim-status tag (Verified / Empirical_fit /
Open_conjecture / Risk / Retracted).  The catalog is stored as a single source
of truth and cross-compiled to Markdown, JSON, Python, Rust, C, and TypeScript
via a template tool.

**Contribution 2: Six bit-exact conformance packs..** 
The packs (Section \ref{sec:packs}) cover the six formats most commonly seen
in current production hardware and research pipelines: GoldenFloat 16 (GF16),
MXFP4 element, BF16, FP8 E4M3, FP8 E5M2, and E8M0 block scale.
Two packs (GF16 and MXFP4) are already live in the `tt-lang-t27`
PyPI package \mbox{v0.3.1}; the remaining four are introduced in the current
pre-release, available at
<https://github.com/gHashTag/tt-lang-t27/pull/6>.

**What this paper is not..** 
This paper presents no model-accuracy benchmarks, no novel format proposals, and
no performance comparisons between vendors.  Readers seeking FLOP throughput
analysis or quantization accuracy results should consult the separate literature.

**Roadmap..** 
Section \ref{sec:background} surveys the relevant standards landscape.
Section \ref{sec:catalog} describes the catalog design.
Section \ref{sec:methodology} defines the conformance pack methodology.
Section \ref{sec:packs} presents each of the six packs in turn.
Section \ref{sec:p3109} provides an IEEE P3109 cross-walk.
Section \ref{sec:discussion} discusses the interpretation gap as a design feature.
Section \ref{sec:repro} covers reproducibility and provenance.
Section \ref{sec:future} outlines future work.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_10$,
  'paper3-methodology'
);

-- paper3-02-background (334 words, SHA-256 be2896f5bf953ecf...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-02-background',
  'chapter',
  200200,
  'Background and Prior Work',
  $p3body_20$# Background and Prior Work

**Claim status:** Verified.

\label{sec:background}

### Floating-Point Standards

IEEE 754-2019 [ieee754] defines binary interchange formats (binary16,
binary32, binary64, binary128) and the rounding, overflow, and NaN rules that
govern them.  BF16 (brain float 16) is not in the 2019 revision; it arose
informally at Google Brain and is now supported across Intel, AMD, ARM, and
NVIDIA hardware, sharing the exponent range of FP32 (8 exponent bits, bias
$= 127$) with a 7-bit mantissa.

The OCP Microscaling (MX) specification v1.0 [ocp_mx] introduces block
formats in which groups of 32 elements share a common E8M0 scale factor.
The element types include MXFP4 (S1E2M1), MXFP6 (E2M3 and E3M2), MXFP8 (E4M3
and E5M2), and MXINT8.  OCP MX explicitly permits two overflow policies for
FP8 E4M3: saturation to max-finite (used by the tt-metal and AMD implementations)
and overflow to NaN (used by JAX/TPU).

IEEE P3109 [p3109_interim] is an active working group standardizing
8-bit and 4-bit floating-point formats for AI workloads.  Its v3.2.0 Interim
Report defines Binary8p3se and Binary4p1sf (among others) and a
`StandardOperations.yaml` catalogue of approximately 80 operations
across seven categories.

### Existing Reference Implementations

**ml_dtypes** [mldtypes] (Google/JAX) is a Python/C++ library
offering reference implementations of `bfloat16`,
`float8_e4m3fn`, `float8_e5m2`, `float8_e8m0fnu`,
and several other formats.  It is the ground-truth oracle used throughout this
work.

**P3109 FLoPS** [flops_lean] is a Lean 4 formalization of the P3109
semantics, providing proof-checked coverage of key operations.

**torch.float8** (PyTorch) and **jax.dtypes** expose FP8 types at
the framework level but do not publish bit-vector test suites independent of
hardware execution.

**MX evaluation** studies [mx_eval] measure accuracy impact of
microscaling quantization in transformer workloads.

### The Gap

No single vendor-neutral artifact currently covers FP8 E4M3, FP8 E5M2, BF16,
MXFP4 element, GoldenFloat 16, and E8M0 block scale in one schema with:
(a) bit-exact encode/decode vectors, (b) SHA-256-anchored provenance, (c) 
explicit documentation of each divergence from the reference implementation,
and (d) a human-readable cross-walk to IEEE P3109.  This work fills that
registry gap.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_20$,
  'paper3-methodology'
);

-- paper3-03-catalog-design (701 words, SHA-256 39b4a3567b5115a6...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-03-catalog-design',
  'chapter',
  200300,
  'Catalog Design',
  $p3body_30$# Catalog Design

**Claim status:** Verified.

\label{sec:catalog}

### 84 Formats Across 13 Clusters

The `t27` catalog contains 84 formats organized into 13 named clusters.
Table \ref{tab:clusters} shows the cluster names and format counts.  The sum
of counts is exactly 84; this is a continuously enforced catalog invariant
(CI-01, Section \ref{sec:invariants}).

```latex
\begin{table}[ht]
\centering
\caption{The 84 formats across 13 clusters (T1).}
\label{tab:clusters}
\begin{tabular}{llr}
\toprule
\textbf{Cluster} & \textbf{Representative formats} & \textbf{Count} \\
\midrule
IEEE754 binary       & binary16, binary32, binary64, binary128, binary80 & 5 \\
IEEE754 decimal      & decimal32, decimal64, decimal128 & 3 \\
MLLowPrecision       & BF16, TF32, FP8 E4M3, FP8 E5M2, FP8 E3M4, FP6, FP4, NF4 & 8 \\
GoldenFloat          & GF4 through GF256 (phi-anchored variants) & 16 \\
Posit / Unum III     & Posit8, Posit16, Posit32, takum8, takum16, \ldots & 8 \\
OCP MX               & MXFP4, MXFP6\_E2M3, MXFP6\_E3M2, MXFP8\_E4M3, E8M0\_block & 5 \\
LNS                  & LNS8, LNS16 variants & 4 \\
IntegerFixed         & INT2, INT4, INT8, INT16, UINT4, UINT8, UINT16, FXP16 & 8 \\
HistoricalVendor     & IBM hex float, DEC VAX G, Cray single, NVIDIA TF32, \ldots & 10 \\
Theoretical          & E0M7, E7M0, E1M6, E6M1 boundary cases & 4 \\
Compression/scaling  & NF4 block, E8M0 block, SF8, RFP8 & 4 \\
Extended             & binary256, bfloat32, bfloat128 & 3 \\
QuantTuned           & Q-BF16, adaptive-FP8 & 2 \\
\midrule
\textbf{Total} & & \textbf{84} \\
\bottomrule
\end{tabular}
\end{table}
```

### One-Row-Per-Format Schema

Each catalog entry carries the following fields:

- \texttt{name} -- canonical identifier (ASCII, no spaces)
- \texttt{bits} -- total bit width
- \texttt{exp} -- exponent field width in bits
- \texttt{mant} -- mantissa field width in bits (0 for E8M0-style)
- \texttt{bias} -- exponent bias
- \texttt{has\_inf} -- boolean
- \texttt{has\_nan} -- boolean
- \texttt{saturation\_policy} -- \texttt{SatFinite}, \texttt{OvfInf}, or \texttt{OvfNaN}
- \texttt{max\_finite} -- largest representable finite value (f64)
- \texttt{min\_normal} -- smallest positive normal value (f64)
- \texttt{min\_subnormal} -- smallest positive subnormal (f64; \texttt{null} if none)
- \texttt{cluster} -- one of the 13 cluster labels
- \texttt{claim\_status} -- Verified / Empirical\_fit / Open\_conjecture / Risk / Retracted

### Claim-Status Taxonomy

**Verified**: format spec is backed by a published standard (IEEE, OCP) or
by a proof-checked reference (P3109 FLoPS Lean).
**Empirical_fit**: derived by fitting the observed bit layout of a hardware
product without an independently published spec.
**Open_conjecture**: proposed generalization awaiting external validation.
**Risk**: spec reference exists but the catalog encoding may contain errors
not yet caught by the test suite.
**Retracted**: previously included; removed after a conflicting authoritative
source was identified.

### Catalog Invariants

\label{sec:invariants}

Fifteen invariants are checked on every commit.  Selected invariants are listed
in Table \ref{tab:invariants}.

```latex
\begin{table}[ht]
\centering
\caption{15 catalog invariants (CI-enforced) (T2).}
\label{tab:invariants}
\begin{tabular}{cll}
\toprule
\textbf{ID} & \textbf{Invariant} & \textbf{Check} \\
\midrule
CI-01 & Total format count equals 84 & \texttt{sum(cluster\_counts) == 84} \\
CI-02 & No name collisions & \texttt{len(names) == len(set(names))} \\
CI-03 & Bit-width consistency & \texttt{1 + exp + mant == bits} for standard layout \\
CI-04 & Bias range & \texttt{bias <= 2**(exp-1) - 1} \\
CI-05 & Saturation policy present & field not null for every entry \\
CI-06 & Max-finite positive & \texttt{max\_finite > 0} \\
CI-07 & Min-normal $\leq$ max-finite & ordering preserved \\
CI-08 & Cluster label in enum & no unlisted cluster names \\
CI-09 & Claim status in enum & no unlisted claim-status values \\
CI-10 & No format with 0 bits & \texttt{bits >= 2} \\
CI-11 & SHA-256 anchor present & each pack header carries fingerprint field \\
CI-12 & Anchor vector present & each pack contains \texttt{anchor\_*} vector \\
CI-13 & Anchor decodes to 3.0 & \texttt{decode(anchor\_bits) == 3.0} \\
CI-14 & Codegen targets compile & CI matrix runs Python + Rust import tests \\
CI-15 & No duplicate SHA-256 & pack fingerprints are globally unique \\
\bottomrule
\end{tabular}
\end{table}
```

### Codegen Path

A single Jinja2 template tool reads the canonical JSON catalog and emits
per-language output files: Markdown (human-readable table), JSON (API export),
Python dataclasses, Rust structs with `serde` derives, C header
(`#define` constants), and TypeScript enum literals.  All generated
files are committed to the repository at <https://github.com/gHashTag/t27>
and rebuilt on every push via a GitHub Actions matrix.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_30$,
  'paper3-methodology'
);

-- paper3-04-conformance-methodology (456 words, SHA-256 402f8bb84bd13fbd...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-04-conformance-methodology',
  'chapter',
  200400,
  'Conformance Pack Methodology',
  $p3body_40$# Conformance Pack Methodology

**Claim status:** Verified.

\label{sec:methodology}

### Shared Row Schema

Every conformance pack is a JSON array of vectors, each row conforming to the
schema shown in Table \ref{tab:schema}.

```latex
\begin{table}[ht]
\centering
\caption{Shared row schema for all conformance packs (T3).}
\label{tab:schema}
\begin{tabular}{lll}
\toprule
\textbf{Field} & \textbf{Type} & \textbf{Description} \\
\midrule
\texttt{name}              & string  & human-readable test-case identifier \\
\texttt{input\_f64}        & number  & input value as a double-precision float \\
\texttt{input\_f64\_hex}   & string  & IEEE 754 hex encoding of the input (f32 or f64) \\
\texttt{<fmt>\_bits\_hex}  & string  & target-format bit pattern, hex \\
\texttt{<fmt>\_bits\_int}  & integer & same bit pattern as an unsigned integer \\
\texttt{decoded\_f64}      & number  & result of decode(encode(input)) \\
\texttt{decoded\_f64\_hex} & string  & IEEE 754 hex encoding of decoded value \\
\texttt{abs\_error}        & number  & $|$input $-$ decoded$|$; always shown (never hidden) \\
\texttt{category}          & string  & zero / normal / subnormal / inf / nan / overflow / \\
                            &         & underflow / rounding / anchor / transcendental \\
\bottomrule
\end{tabular}
\end{table}
```

### Pack Header

In addition to the vector array, each pack file carries a header object with
the following fields:

- Format spec quadruple: $(E, M, \text{bias}, \text{infNaN policy})$
- Saturation policy
- Max-finite value
- SHA-256 self-fingerprint (computed over the canonical JSON serialization)
- \texttt{ml\_dtypes} version anchor
- Anchor identity reference: \texttt{phi\^{}2 + 1/phi\^{}2 = 3 (arXiv:2606.05017)}

### Anchor Vector

Every pack contains at least one vector named `anchor_*` that encodes
the value $3.0$.  The motivation is the identity
```latex
\begin{equation}
  \varphi^{2} + \frac{1}{\varphi^{2}} = 3,
  \label{eq:anchor}
\end{equation}
```
where $\varphi = (1 + \sqrt{5})/2$ is the golden ratio.  This identity is
presented and contextualized in the GoldenFloat preprint [gf_arxiv] as a
numerically grounded $L_2$ anchor.  The value $3.0$ is exactly representable in
all six pack formats (it falls in the normal range with zero mantissa error
for all six layouts), making it a reliable single-line sanity check across packs.

Formally: for any pack format $F$, if $`decode`_F(`encode`_F(3.0))
\neq 3.0$, a fundamental implementation error is present.

### Verification Steps

Each pack is checked by two independent procedures:

1. \textbf{Round-trip self-check.} For each vector: $\texttt{decode}(\texttt{encode}(\texttt{input})) = \texttt{decoded}$, with the stored \texttt{abs\_error} consistent with the deviation.
2. \textbf{Cross-check against ml\_dtypes 0.5.4.} Where a corresponding ml\_dtypes type exists, the pack's bit patterns are compared against the ml\_dtypes encoding of the same inputs.  Every divergence is recorded in the pack header's \texttt{divergences} list and described in this paper.

Honest treatment of absolute error is a non-negotiable design principle.
Every vector where the decoded value differs from the input carries a nonzero
`abs_error`; no value is suppressed or rounded to zero to make match
statistics look better.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_40$,
  'paper3-methodology'
);

-- paper3-05-six-packs (893 words, SHA-256 fb391b6446a184bc...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-05-six-packs',
  'chapter',
  200500,
  'The Six Conformance Packs',
  $p3body_50$# The Six Conformance Packs

**Claim status:** Empirical fit.

\label{sec:packs}

Table \ref{tab:sixpacks} gives a summary of all six packs.

```latex
\begin{table}[ht]
\centering
\caption{Six packs at a glance (T4).}
\label{tab:sixpacks}
\begin{tabular}{llrrll}
\toprule
\textbf{Pack} & \textbf{Layout} & \textbf{Vecs} & \textbf{ml\_dtypes match} &
\textbf{Status} & \textbf{SHA-256 (first 16 hex)} \\
\midrule
GF16          & S1E5M10 phi-anchored & 21 & n/a (no ml\_dtypes equiv.) & LIVE v0.3.1 & see repo \\
MXFP4         & S1E2M1 block element & 12 & n/a & LIVE v0.3.1 &
  \texttt{86c99d6f72375d75} \\
BF16          & S1E8M7 bias=127, RTE & 21 & 21/21 & NEW v0.4.0-pre &
  \texttt{320c1850b4846745} \\
FP8 E4M3      & S1E4M3 bias=7, SatMax & 16 & 15/16 (see Sec.~\ref{sec:discussion}) & NEW v0.4.0-pre &
  \texttt{fff0c30f8e6bee22} \\
FP8 E5M2      & S1E5M2 bias=15, OvfInf & 17 & 17/17 & NEW v0.4.0-pre &
  \texttt{66cd7be1500ec800} \\
E8M0 block    & E8M0 scale-only, no sign & 11 & OCP MX v1.0 aligned & NEW v0.4.0-pre &
  \texttt{b211f1a863f71fd7} \\
\bottomrule
\end{tabular}
\end{table}
```

Full SHA-256 fingerprints (verbatim from the manifest):
- \textbf{GF16}: see repository (SHA-256 not yet pinned in v0.4.0-pre manifest)
- \textbf{MXFP4}: \texttt{86c99d6f72375d751df4c74897904a0a36cff52e8d60cbfef5d58b71625d4b2f}
- \textbf{BF16}: \texttt{320c1850b484674546785791b1c22d76feb4ea748c6669ffb633e5455d822b8a}
- \textbf{FP8 E4M3}: \texttt{fff0c30f8e6bee22b1a7d0e0e1cff65edde9d2b17ebf97dba0539973f0a5e89d}
- \textbf{FP8 E5M2}: \texttt{66cd7be1500ec8003eb5dee7532bb4e954b7bc0084b6f22a75d02f7842f23a56}
- \textbf{E8M0 block}: \texttt{b211f1a863f71fd7c5e02e512efff0255ebcc51521311186e01cb9992e4464bd}

### GF16 -- GoldenFloat 16-bit

\label{sec:pack_gf16}

GF16 is a 16-bit format using layout S1E5M10 with a phi-rotation of the
representable range.  It is described and motivated in the GoldenFloat
preprint [gf_arxiv].  The pack contains 21 vectors covering zero,
normal values, the anchor $3.0$ (encoding the identity
$\varphi^{2} + 1/\varphi^{2} = 3$, Eq. \eqref{eq:anchor}), subnormals, and
overflow behavior.  Because ml_dtypes does not implement a GF16 type, this pack
has no cross-validation partner; its vectors are verified by the round-trip
self-check only.  GF16 has been live in the `tt-lang-t27` PyPI package
since v0.3.1.

### MXFP4 Element -- OCP Microscaling 4-bit

\label{sec:pack_mxfp4}

MXFP4 element uses layout S1E2M1 (1 sign, 2 exponent, 1 mantissa bit) with
saturation-to-finite overflow policy, as specified in OCP MX v1.0 [ocp_mx].
Within a block, 32 such elements share an E8M0 scale factor.  The element pack
covers 12 vectors: the 15 representable finite values plus zero and the
saturation case.  ml_dtypes does not expose an MXFP4 element type at the time
of writing; the pack is verified by round-trip self-check and compared against
the OCP MX v1.0 value table.
SHA-256:
`86c99d6f72375d751df4c74897904a0a36cff52e8d60cbfef5d58b71625d4b2f`.

### BF16 -- Brain Float 16

\label{sec:pack_bf16}

BF16 uses layout S1E8M7 with bias $= 127$, round-to-nearest-even (RTE), and
IEEE 754-style handling of infinity and NaN.  It occupies the upper 16 bits of
an FP32 word, so conversion to/from FP32 is a simple truncation (with
rounding).  The pack contains 21 vectors, including:
- Positive and negative zero
- Positive and negative infinity (preserved exactly)
- Quiet NaN (preserved with payload)
- Smallest positive normal and subnormal
- Largest finite BF16 ($\approx 3.39 \times 10^{38}$)
- Two RTE midpoint cases (round-to-even behavior)
- Overflow of FP32 max into BF16 $+\infty$ (abs\_error $= +\infty$)
- Underflow of FP32 min-subnormal to BF16 $+0$
- Non-exact constants $\varphi$ and $1/\varphi$ with nonzero abs\_error
- The anchor vector at $3.0$ (exact, abs\_error $= 0$)
All 21 vectors match `ml_dtypes.bfloat16` (Google/JAX 0.5.4): 21/21.
SHA-256:
`320c1850b484674546785791b1c22d76feb4ea748c6669ffb633e5455d822b8a`.

BF16 exhibits high inter-vendor agreement; Google bfloat16, Intel BFLOAT16,
ARM BFloat16, and NVIDIA TF32-paired BF16 share the same IEEE 754-style
sub/inf/NaN semantics with round-to-nearest-even on the lower 16 bits of FP32.
No notable divergences were observed in the 21 boundary cases tested.

### FP8 E4M3 -- Eight-bit Float with Four-bit Exponent

\label{sec:pack_fp8e4m3}

FP8 E4M3 uses layout S1E4M3 with bias $= 7$.  In the OCP MX variant (used
here), infinity is replaced by additional finite values, and NaN is encoded as
bit pattern `0x7F` (or `0xFF` for negative).  The format thus
has no $+\infty$, giving a max-finite value of $448.0$.

The pack contains 16 vectors.  15 of 16 match `ml_dtypes.float8_e4m3fn`
exactly.  The single documented divergence is the overflow case for input
$1000.0$, detailed in Table \ref{tab:overflow_gap} and discussed in
Section \ref{sec:discussion}.
SHA-256:
`fff0c30f8e6bee22b1a7d0e0e1cff65edde9d2b17ebf97dba0539973f0a5e89d`.

```latex
\begin{table}[ht]
\centering
\caption{FP8 E4M3 overflow interpretation gap for input $1000.0$ (T5).}
\label{tab:overflow_gap}
\begin{tabular}{lllll}
\toprule
\textbf{Input} & \textbf{Implementation} & \textbf{Bits} & \textbf{Decoded} & \textbf{Policy} \\
\midrule
$1000.0$ & this pack (tt-metal/AMD convention) & \texttt{0x7E} & $448.0$ (max-finite) & saturate-to-max \\
$1000.0$ & ml\_dtypes 0.5.4 (JAX/TPU convention) & \texttt{0x7F} & NaN & overflow-to-NaN \\
\midrule
\multicolumn{5}{l}{\small Both choices are permitted by OCP MX v1.0. See Section~\ref{sec:discussion}.} \\
\bottomrule
\end{tabular}
\end{table}
```

### FP8 E5M2 -- Eight-bit Float with Five-bit Exponent

\label{sec:pack_fp8e5m2}

FP8 E5M2 uses layout S1E5M2 with bias $= 15$ and retains full IEEE 754-style
infinity and NaN.  Max-finite is $57344.0$.  The pack contains 17 vectors
covering the complete boundary suite (zero, normals, subnormals, $\pm\infty$,
NaN, overflow, underflow, RTE midpoints, and the anchor $3.0$).
All 17 vectors match `ml_dtypes.float8_e5m2` exactly: 17/17.
SHA-256:
`66cd7be1500ec8003eb5dee7532bb4e954b7bc0084b6f22a75d02f7842f23a56`.

### E8M0 Block Scale -- OCP Microscaling Scale Format

\label{sec:pack_e8m0}

E8M0 is a scale-only format used as the shared block exponent in OCP MX blocks.
It carries no sign bit and no mantissa -- only 8 exponent bits representing
powers of 2 in the range $[2^{-127}, 2^{127}]$.  The special pattern `0xFF`
encodes NaN (used to indicate an uninitialized or invalid scale).
The pack contains 11 vectors covering representative scale values, the NaN
sentinel, and the anchor $3.0$ (which encodes to the closest representable
power-of-two scale, $2^1 = 2$, with a documented nonzero abs_error).
Vectors were regenerated against `ml_dtypes.float8_e8m0fnu` (Google/JAX
0.5.4) following OCP MX v1.0 semantics.
SHA-256:
`b211f1a863f71fd7c5e02e512efff0255ebcc51521311186e01cb9992e4464bd`.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_50$,
  'paper3-methodology'
);

-- paper3-06-p3109-crosswalk (410 words, SHA-256 35e544eab4b35851...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-06-p3109-crosswalk',
  'chapter',
  200600,
  'IEEE P3109 Cross-Walk',
  $p3body_60$# IEEE P3109 Cross-Walk

**Claim status:** Open conjecture.

\label{sec:p3109}

IEEE P3109 [p3109_interim] is an active working group standardizing
floating-point arithmetic for AI applications.  Its v3.2.0 Interim Report
defines a family of configured formats parameterized by $(E, M, \text{saturation})$.

Table \ref{tab:p3109} maps the six packs to P3109 v3.2.0 configured formats.

```latex
\begin{table}[ht]
\centering
\caption{P3109 v3.2.0 cross-walk for the six packs (T6).}
\label{tab:p3109}
\begin{tabular}{lllll}
\toprule
\textbf{Our format} & \textbf{P3109 name} & \textbf{Match} & \textbf{Key difference} & \textbf{Pack} \\
\midrule
FP8 E4M3  & Binary8p3se & Close & Saturation: ours SatMax vs. P3109 OvfInf;
                                   finite-only NaN encoding & \texttt{fp8\_e4m3} \\
MXFP4 element & Binary4p1sf & Direct & Block structure orthogonal; element matches & \texttt{mxfp4} \\
GF16      & (none)       & No match & P3109 does not address 16-bit phi-anchored formats & \texttt{gf16} \\
BF16      & (none)       & No match & P3109 focuses on 4/8-bit; BF16 is 16-bit & \texttt{bf16} \\
FP8 E5M2  & (none)       & No match & Binary8p2se would correspond but is absent in v3.2.0 & \texttt{fp8\_e5m2} \\
E8M0 block & (none)      & Orthogonal & P3109 does not define a scale-only format & \texttt{e8m0\_block} \\
\bottomrule
\end{tabular}
\end{table}
```

### Direct Matches

**Binary8p3se $\leftrightarrow$ FP8 E4M3.**
P3109 Binary8p3se specifies S1E4M3 with OvfInf saturation.  The OCP MX v1.0
FP8 E4M3 variant used in this pack employs SatMax instead.  The difference is
exactly the overflow interpretation gap documented in Table \ref{tab:overflow_gap}.
Aside from this saturation policy choice, the bit layouts and bias are identical.

**Binary4p1sf $\leftrightarrow$ MXFP4 element.**
P3109 Binary4p1sf specifies S1E2M1 with SatFinite -- identical to the MXFP4
element layout in OCP MX v1.0.  The only structural difference is that OCP MX
wraps elements in 32-element blocks sharing an E8M0 scale factor, a block
dimension that P3109 does not address in v3.2.0.

### Partial and Non-Matches

FP8 E5M2 would map to a hypothetical Binary8p2se, which is absent from P3109
v3.2.0 Profiles.  GF16 and BF16 are outside the 4/8-bit scope that P3109
currently addresses.  E8M0 is a scale-only format orthogonal to P3109's
representation layer.

### Operational Coverage

P3109's `StandardOperations.yaml` enumerates approximately 80 operations
across seven categories: Classification (8), Comparison (7), Extrema
(10+), Projection rounding (6 modes), Math arithmetic (10), Math
transcendental ($\approx$25), and Block operations (40+).

The current suite (v0.1) covers only the _representation layer_ --
encode/decode bit-exactness.  Track 2 (target Q3 2026) will extend coverage to
the operation layer, at minimum NearestTiesToEven rounding for Add, Multiply,
and FMA across all six formats.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_60$,
  'paper3-methodology'
);

-- paper3-07-discussion-interpretation-gap (289 words, SHA-256 2743b615795ae474...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-07-discussion-interpretation-gap',
  'chapter',
  200700,
  'Discussion: The Interpretation Gap as Ruler Value',
  $p3body_70$# Discussion: The Interpretation Gap as Ruler Value

**Claim status:** Empirical fit.

\label{sec:discussion}

A conformance suite earns its keep not when all vectors match, but when it
exposes a divergence that would otherwise be invisible.  The FP8 E4M3 overflow
case (input $= 1000.0$) is precisely such a case.

The OCP MX v1.0 specification [ocp_mx] states that for inputs exceeding
max-finite ($448.0$ for E4M3), implementations may either saturate to max-finite
or produce NaN.  Two mature, production-quality implementations make different
choices:

- \textbf{tt-metal (Tenstorrent) / AMD convention}: saturate to max-finite.  Bit pattern \texttt{0x7E}, decoded value $448.0$. This pack adopts this convention.
- \textbf{JAX/TPU convention (ml\_dtypes 0.5.4)}: overflow to NaN. Bit pattern \texttt{0x7F}, decoded value NaN.

Neither choice is a bug.  Both are compliant with OCP MX v1.0.  The divergence
is a documented spec-permitted interpretation gap.

The practical implication is significant for compiler and test-harness
authors.  Any cross-vendor port of an FP8 E4M3 computation must either:
(a) select one policy explicitly and document it, or
(b) carry both vectors in its golden-reference test suite, accepting that
overflow-range inputs will produce differing results on different hardware.

This is precisely what a conformance pack is designed to expose.  A test suite
that compares only ``do the outputs match on this hardware?'' would never see
this divergence -- both implementations pass their own tests.  A shared bit-exact
reference makes the gap visible.

Honesty norm: every vector in every pack where the decoded value differs from
the input carries a nonzero `abs_error`.  Overflow to $\pm\infty$ shows
`abs_error = Inf`; underflow to zero shows the actual magnitude of the
underflowed value.  No abs_error field is suppressed or rounded to zero to
improve match statistics.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_70$,
  'paper3-methodology'
);

-- paper3-08-reproducibility-provenance (347 words, SHA-256 07a10e84b60d761f...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-08-reproducibility-provenance',
  'chapter',
  200800,
  'Reproducibility and Provenance',
  $p3body_80$# Reproducibility and Provenance

**Claim status:** Verified.

\label{sec:repro}

### Source Repositories

- \textbf{gHashTag/t27} (\url{https://github.com/gHashTag/t27}): the single source of truth (SSOT) for the catalog and Tier-1 conformance packs. All JSON catalog files, pack files, invariant checks, and codegen templates live here.
- \textbf{gHashTag/tt-lang-t27} (\url{https://github.com/gHashTag/tt-lang-t27}): PyPI mirror.  Version 0.3.1 is live on PyPI (GF16 and MXFP4 packs included).  Version 0.4.0-pre, adding the four new packs described in this paper, is available in \href{https://github.com/gHashTag/tt-lang-t27/pull/6}{PR~\#6}.
- \textbf{gHashTag/tt-trinity-corona} (\url{https://github.com/gHashTag/tt-trinity-corona}): Tier-2 silicon oracle context for post-silicon audit on GF180MCU; one-line mention here for completeness.

### Ground-Truth Tool

The primary oracle for all cross-validation is `ml_dtypes` 0.5.4
[mldtypes] (Google/JAX), available at
<https://github.com/jax-ml/ml_dtypes>.  The specific types used are:
`ml_dtypes.bfloat16`, `ml_dtypes.float8_e4m3fn`,
`ml_dtypes.float8_e5m2`, and `ml_dtypes.float8_e8m0fnu`.

### Anchor Fingerprint

The anchor identity $\varphi^{2} + 1/\varphi^{2} = 3$ (Eq. \eqref{eq:anchor}),
as formalized in the GoldenFloat preprint [gf_arxiv], has the following
canonical SHA-256 fingerprint:
\begin{center}
`218403e344779c890f302ad2c70af21fb765060dd794d793c7eacc1ef8f80e6b`
\end{center}
This fingerprint covers the canonical UTF-8 encoding of the identity string and
serves as an out-of-band check that the correct anchor paper is being cited.

### Pack Provenance Table

Table \ref{tab:provenance} lists the repository path, branch/PR, and full
SHA-256 for each pack.

```latex
\begin{table}[ht]
\centering
\caption{Pack-to-provenance mapping (T7).}
\label{tab:provenance}
\begin{tabular}{lllp{5.5cm}}
\toprule
\textbf{Pack} & \textbf{Repo} & \textbf{Branch / PR} & \textbf{Full SHA-256} \\
\midrule
GF16 & gHashTag/t27 & \texttt{main} (v0.3.1) & see repo (not pinned in v0.4.0-pre manifest) \\
MXFP4 & gHashTag/t27 & \texttt{main} (v0.3.1) &
  \texttt{86c99d6f72375d751df4c74897904a0a36cff} \newline \texttt{52e8d60cbfef5d58b71625d4b2f} \\
BF16 & gHashTag/t27 & PR~\#6 (v0.4.0-pre) &
  \texttt{320c1850b484674546785791b1c22d76feb4} \newline \texttt{ea748c6669ffb633e5455d822b8a} \\
FP8 E4M3 & gHashTag/t27 & PR~\#6 (v0.4.0-pre) &
  \texttt{fff0c30f8e6bee22b1a7d0e0e1cff65edde9} \newline \texttt{d2b17ebf97dba0539973f0a5e89d} \\
FP8 E5M2 & gHashTag/t27 & PR~\#6 (v0.4.0-pre) &
  \texttt{66cd7be1500ec8003eb5dee7532bb4e954b7} \newline \texttt{bc0084b6f22a75d02f7842f23a56} \\
E8M0 block & gHashTag/t27 & PR~\#6 (v0.4.0-pre) &
  \texttt{b211f1a863f71fd7c5e02e512efff0255ebc} \newline \texttt{c51521311186e01cb9992e4464bd} \\
\bottomrule
\end{tabular}
\end{table}
```

### Manifest

The file `MANIFEST_v0.4.0-pre.json` in the `gHashTag/t27`
repository records all six pack SHA-256 values, the ml_dtypes version anchor,
and the P3109 alignment reference in a single machine-readable document.
Downstream consumers can verify pack integrity by recomputing the SHA-256 of
the canonical JSON file and comparing against the manifest entry.

## References {.unnumbered}

_Inline citations resolved in the paper-level bibliography (see Reproducibility section)._
$p3body_80$,
  'paper3-methodology'
);

-- paper3-09-future-work (255 words, SHA-256 6d1cceb612602723...)
INSERT INTO ssot_brochure.chapters (slug, kind, order_key, title, body_md, doc) VALUES (
  'paper3-09-future-work',
  'chapter',
  200900,
  'Future Work',
  $p3body_90$# Future Work

**Claim status:** Open conjecture.

\label{sec:future}

### Track 2: Full 84-Pack Suite

The six packs in this paper cover the formats most immediately relevant to
production ML hardware.  Track 2 (target Q3 2026) will extend coverage to
all 84 catalog formats for which reference implementations are available,
including the remaining MLLowPrecision entries (FP6, FP4, NF4),
Posit/Unum III types, and GoldenFloat variants GF4 through GF256.

### Operation-Layer Conformance

The current suite covers the representation layer only.  Track 2 will add
operation-layer vectors aligned with the P3109 `StandardOperations.yaml`
subset, beginning with NearestTiesToEven rounding for Add, Multiply, and FMA
across all six current formats.  This will allow compiler and hardware teams to
validate not only that they encode/decode correctly, but that their arithmetic
operations agree with the standard at the bit level.

### Round-Trip Fuzzing

A property-based fuzzer will complement the hand-crafted boundary vectors.
The fuzzer will generate random FP32 inputs, apply encode/decode for each
format, and assert the round-trip property and abs_error consistency.  This
is particularly valuable for formats with complex saturation behavior.

### Open Invitations

Maintainers of ml_dtypes, OCP MX, IEEE P3109, IREE, vllm, llama.cpp, and
onnxruntime are invited to consume the catalog as a cross-walk substrate,
validate the pack vectors against their implementations, and report divergences
as GitHub issues on `gHashTag/t27`.  Any new divergence found is a
feature of the ruler, not a failure of the suite.

The conformance packs, catalog schema, and codegen templates are open-licensed
with the intent that they become a shared community resource for vendor-neutral
numeric format registry work.
$p3body_90$,
  'paper3-methodology'
);

-- Postflight: confirm 9 rows inserted
SELECT 'paper3_rows' AS step, COUNT(*) AS n FROM ssot_brochure.chapters WHERE doc='paper3-methodology';
SELECT slug, order_key, title FROM ssot_brochure.chapters WHERE doc='paper3-methodology' ORDER BY order_key;

COMMIT;

-- ====================================================================
-- Rollback (delete paper3-methodology rows):
--   BEGIN;
--   DELETE FROM ssot_brochure.chapters WHERE doc='paper3-methodology';
--   COMMIT;
-- ====================================================================
